### PR TITLE
Fix problems mentioned in issue #6

### PR DESCRIPTION
**Pull request by ciprianjichici**
Fixes the first, third, fourth, and fifth problems mentioned in issue #6.
The second problem is solved by changes from PR #7.
Regarding the sixth problem, the `embeddings` container is currently not used in the code.

### CODE REVIEW

**Comment by markjbrown** [comment]
can you remove embedding container from ARM template? It burns through RU even if unused.

**Comment by markjbrown** [comment]
Can you comment any class in this solution that is not used. Similar to Cog Search in the Search Service. Please use big letters!!!!

**Comment by ciprianjichici** [comment]
@markjbrown , addressed all the comments, please let me know if we're good to merge this.

**Comment by markjbrown** [comment]
Merge it

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
